### ISSUE TITLE
Inconsistency in widths of the session/session series in Professor View

### ISSUE THREAD

**Issue by ngwattcos** [cornell-dti/office-hours#392]
![image](https://user-images.githubusercontent.com/18223523/93716921-6d647400-fb40-11ea-9685-6ba111b5695e.png)

**Comment by asharonbaltazar** [comment]
Hello, I'd like to get started and perhaps address this issue. The setup link in the README isn't working, though.

**Comment by abcdefguan** [comment]
This issue is likely caused by the rows with no location interleaving with rows with locations.
A <td> needs to be generated for the location field whether or not a location is provided.
However, it appears that <td> is not generated when there is no location field.
<img width="1566" alt="Screen Shot 2020-10-01 at 11 48 55 PM" src="https://user-images.githubusercontent.com/9957585/94886314-c2f22800-0440-11eb-932f-7430ccb2f5f1.png">
